set(ExportRoot ${CMAKE_CURRENT_LIST_DIR})

function(ModuleExports Module Directory)
    set(ModuleName ${Module})
    configure_file(${ExportRoot}/Exports.h.in ${Directory}/${Module}Exports.generated.h @ONLY)
    target_compile_definitions(${Module} PRIVATE -D${Module}_Impl)
endfunction()

function(FindTargets TargetList Directory)
    set(Target)
    FindTargetsRecursive(TargetList ${Directory})
    set(${TargetList} ${Target} PARENT_SCOPE)
endfunction()

macro(FindTargetsRecursive TargetList Directory)
    get_property(SubDirectories DIRECTORY ${Directory} PROPERTY SUBDIRECTORIES)
    foreach(SubDirectory ${SubDirectories})
        FindTargetsRecursive(${TargetList} ${SubDirectory})
    endforeach()

    get_property(FoundTargets DIRECTORY ${Directory} PROPERTY BUILDSYSTEM_TARGETS)
    list(APPEND ${TargetList} ${FoundTargets})
endmacro()

function(ModuleWall Module)
    if (MSVC)
        target_compile_options(${Module} PRIVATE /W4 /WX)
    else()
        target_compile_options(${Module} PRIVATE -Wall -Wextra -pedantic -Werror)
    endif()
endfunction()

function(AddModule Directory)
    add_subdirectory(${Directory})
    FindTargets(Targets ${Directory})
    foreach(Target ${Targets})
        message("Module: ${Target}")
        ModuleWall(${Target})
    endforeach()
endfunction()
