#include "Reflector.hpp"
#include <filesystem>
#include <fstream>
#include "ModuleInfo.hpp"
#include <string>
#include <string_view>
#include "FileParser.hpp"

static void reflectEntry(const ReflectedEntry* entry, std::ofstream& file);

static void reflectClass(const ReflectedClass* entry, std::ofstream& file)
{
    file << "ReflectedClass " + entry->name + "(\"" + entry->name + "\", {\n";

    for (auto member : entry->members)
    {
        reflectEntry(member, file);
    }

    file << "});\n";
}

static void reflectStruct(const ReflectedClass* entry, std::ofstream& file)
{
    file << "// Reflected struct: " << entry->name << "\n";

    for (auto member : entry->members)
    {
        reflectEntry(member, file);
    }
}

static void reflectFunction(const ReflectedFunction* entry, std::ofstream& file)
{
    file << "\tnew ReflectedClassMemberFunction(\"" << entry->name << "\"),\n";
}

static void reflectVariable(const ReflectedVariable* entry, std::ofstream& file)
{
    file << "\tnew ReflectedClassMemberVariable(\"" << entry->name << "\"),\n";
}


static void reflectEntry(const ReflectedEntry* entry, std::ofstream& file)
{
    switch (entry->type)
    {
	    case RT_Class:
	    {
	        reflectClass(dynamic_cast<const ReflectedClass*>(entry), file);
	        break;
	    }

	    case RT_Struct:
	    {
	        reflectStruct(dynamic_cast<const ReflectedClass*>(entry), file);
	        break;
	    }
	    case RT_Variable:
	    {
	        reflectVariable(dynamic_cast<const ReflectedVariable*>(entry), file);
	        break;
	    }
	    case RT_Function:
	    {
	        reflectFunction(dynamic_cast<const ReflectedFunction*>(entry), file);
	        break;
	    }
    }
}


bool Reflector::generateFileReflection(const ModuleManifest* moduleManifest, unsigned int fileIndex)
{
    std::filesystem::path file = moduleManifest->sourceFile(fileIndex);
    std::ifstream fileStream(file);

    fileStream.seekg(0, std::ios::end);
    size_t size = fileStream.tellg();
    std::string fileBuffer(size, ' ');
    fileStream.seekg(0);
    fileStream.read(fileBuffer.data(), size);

    std::vector<ReflectedEntry*> entries;
    if (!fileReflector.reflect(fileBuffer, entries))
    {
        return false;
    }

    std::filesystem::path generatedFolder = moduleManifest->getGeneratedDirectory();
    if (!std::filesystem::exists(generatedFolder))
    {
        create_directories(generatedFolder);
    }

    std::filesystem::path filePath = generatedFolder / ("Reflection" + file.filename().string() + ".cpp");

    std::ofstream outStream(filePath);

    outStream << "// This file is automatically generated. Do not manually change it!\n\n#include <Utils/ReflectionTypes.hpp>\n\n";

    for (const ReflectedEntry* entry : entries)
    {
        reflectEntry(entry, outStream);
    }

    outStream << "std::vector<const ReflectedType*> " + std::string(moduleManifest->name()) + "_Reflection() const {\n\treturn {\n";

    if (!entries.empty())
    {    	
        for (const ReflectedEntry* entry : entries)
        {
            outStream << "\t\t&" + entry->name + ",\n";

            Utility::PrintLineD("Reflected " + entry->name);
            delete entry;
        }
    }

    outStream << "\t}\n;}";

    //TODO Generate class header

    outStream.close();

    return true;
}

bool Reflector::generateModuleReflection(const ModuleManifest* module)
{
    for (unsigned int sourceIndex = 0; sourceIndex < module->sourceFiles(); sourceIndex++)
    {
        std::filesystem::path file = module->sourceFile(sourceIndex);

        //TODO Only reflect when data is missing or outdated
        if (Utility::IsIncludeFile(file.string().c_str()))
        {
            Reflector::generateFileReflection(module, sourceIndex);
        }
    }

    //TODO Write XXXReflection.cpp per module

    //TODO Add generated file to source for compilation

    return true;
}
