#include "Reflector.hpp"
#include <filesystem>
#include <fstream>
#include "ModuleInfo.hpp"
#include <string>
#include "FileParser.hpp"
#include "ProjectInfo.hpp"

static void reflectEntry(const ReflectedEntry* entry, std::ofstream& file);

static void reflectClass(const ReflectedClass* entry, std::ofstream& file)
{
    file << "ReflectedClass " + entry->name + "(\"" + entry->name + "\", {\n";

    for (auto member : entry->members)
    {
        reflectEntry(member, file);
    }

    file << "});\n";
}

static void reflectStruct(const ReflectedClass* entry, std::ofstream& file)
{
    file << "// Reflected struct: " << entry->name << "\n";

    for (auto member : entry->members)
    {
        reflectEntry(member, file);
    }
}

static void reflectFunction(const ReflectedFunction* entry, std::ofstream& file)
{
    file << "\tnew ReflectedClassMemberFunction(\"" << entry->name << "\"),\n";
}

static void reflectVariable(const ReflectedVariable* entry, std::ofstream& file)
{
    file << "\tnew ReflectedClassMemberVariable(\"" << entry->name << "\"),\n";
}


static void reflectEntry(const ReflectedEntry* entry, std::ofstream& file)
{
    switch (entry->type)
    {
	    case RT_Class:
	    {
	        reflectClass(dynamic_cast<const ReflectedClass*>(entry), file);
	        break;
	    }

	    case RT_Struct:
	    {
	        reflectStruct(dynamic_cast<const ReflectedClass*>(entry), file);
	        break;
	    }
	    case RT_Variable:
	    {
	        reflectVariable(dynamic_cast<const ReflectedVariable*>(entry), file);
	        break;
	    }
	    case RT_Function:
	    {
	        reflectFunction(dynamic_cast<const ReflectedFunction*>(entry), file);
	        break;
	    }
    }
}

std::string string_hash(const std::string& string)
{
    std::hash<std::string> hasher;
    auto hashed = hasher(string);
    return std::to_string(hashed);
}

void get_reflection_paths(const ModuleManifest* moduleManifest, const std::filesystem::path& path, std::filesystem::path& header, std::filesystem::path& source, std::string& hash)
{
    std::filesystem::path generatedFolder = moduleManifest->getGeneratedDirectory();
    if (!std::filesystem::exists(generatedFolder))
    {
        create_directories(generatedFolder);
    }

    header = generatedFolder / path.filename().replace_extension(".generated.hpp");
    source = generatedFolder / path.filename().replace_extension(".generated.cpp");

    hash = string_hash(path.string());
}

bool Reflector::generateFileReflection(const ModuleManifest* moduleManifest, unsigned int fileIndex)
{
    std::filesystem::path file = moduleManifest->sourceFile(fileIndex);
    std::ifstream fileStream(file);

    fileStream.seekg(0, std::ios::end);
    size_t size = fileStream.tellg();
    std::string fileBuffer(size, ' ');
    fileStream.seekg(0);
    fileStream.read(fileBuffer.data(), size);

    std::vector<ReflectedEntry*> entries;
    if (!fileReflector.reflect(fileBuffer, entries))
    {
        return false;
    }

    std::filesystem::path _header, filePath;
    std::string hash;
    get_reflection_paths(moduleManifest, file, _header, filePath, hash);

    std::ofstream outStream(filePath);
    outStream << "// This file is automatically generated. Do not manually change it!\n\n#include <Util/ReflectionTypes.hpp>\n\n";

    for (const ReflectedEntry* entry : entries)
    {
        reflectEntry(entry, outStream);
    }

    outStream << "std::vector<const ReflectedType*> Reflect" + hash + "() {\n\treturn {\n";

    if (!entries.empty())
    {    	
        for (const ReflectedEntry* entry : entries)
        {
            outStream << "\t\t&" + entry->name + ",\n";

            Utility::PrintLineD("Reflected " + entry->name);
            delete entry;
        }
    }

    outStream << "\t};\n}";

    //TODO Generate class header

    outStream.close();

    return true;
}

bool Reflector::generateModuleReflection(const ModuleManifest* module)
{
    std::vector<std::string> hashes;

    for (unsigned int sourceIndex = 0; sourceIndex < module->sourceFiles(); sourceIndex++)
    {
        std::filesystem::path file = module->sourceFile(sourceIndex);

        //TODO Only reflect when data is missing or outdated
        //TODO Delete reflection files if nothing has been reflected
        if (Utility::IsIncludeFile(file.string().c_str()))
        {
            Reflector::generateFileReflection(module, sourceIndex);
        }

        std::filesystem::path _header, source;
        std::string hash;
        get_reflection_paths(module, file, _header, source, hash);

        if (std::filesystem::exists(source))
        {
            hashes.push_back(hash);
        }
    }

    auto filePath = module->getGeneratedDirectory() / (std::string(module->name()) + "Reflection.cpp");

    std::ofstream outStream(filePath);
    outStream << "// This file is automatically generated. Do not manually change it!\n\n#include <Util/ReflectionTypes.hpp>\n\n";

    for (const std::string& hash : hashes)
    {
        outStream << "extern std::vector<const ReflectedType*> Reflect" << hash << "();\n";
    }

    outStream << "std::vector<std::vector<const ReflectedType*>(*)()> " + std::string(module->name()) + "ReflectionMembers = {";
    for (const std::string& hash : hashes)
    {
        outStream << "Reflect" << hash << ",";
    }
    outStream << "};\n\n";

    outStream << "std::vector<const ReflectedType*> Reflect" + std::string(module->name()) + "() {\n" \
    "\tstd::vector<const ReflectedType*> types;\n" \
    "\tfor (auto memberRegistration : " + std::string(module->name()) + "ReflectionMembers) {\n" \
    "\t\tfor (const ReflectedType* moduleType : memberRegistration()) {\n" \
    "\t\t\ttypes.push_back(moduleType);\n" \
    "\t\t}\n" \
    "\t}\n" \
    "\treturn types;\n" \
    "}\n";

    if (module->moduleType() == MT_Executable)
    {
        std::vector<std::string> moduleFunctions = { "Reflect" + std::string(module->name()) };

        std::vector<ModuleManifest*> dependencies = module->moduleDependencies();
        for (ModuleManifest* dependency : dependencies)
        {
            std::string name = "Reflect" + std::string(dependency->name());
            moduleFunctions.push_back(name);
            outStream << "\nextern std::vector<const ReflectedType*> " << name << "();";
        }

        outStream << "\n\nstd::vector<std::vector<const ReflectedType*>(*)()> GlobalReflectionTypeFunctions = {";
        for (const std::string& function : moduleFunctions)
        {
            outStream << function << ",";
        }
        outStream << "};\n\n";

        outStream << "std::vector<const ReflectedType*> registerReflectionTypes() {\n" \
            "\tstd::vector<const ReflectedType*> types;\n" \
            "\tfor (auto memberRegistration : GlobalReflectionTypeFunctions) {\n" \
            "\t\tfor (const ReflectedType* moduleType : memberRegistration()) {\n" \
            "\t\t\ttypes.push_back(moduleType);\n" \
            "\t\t}\n" \
            "\t}\n" \
            "\treturn types;\n" \
            "}\n";
    }

    return true;
}
