name: FaroEngine Documentation

on:
  push:
    branches:
      - main

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Generate
      run: cmake ./Docs
      
    - name: Build
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        doxyfile-path: 'Docs/Doxygen'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FaroEngineDocumentation
        if-no-files-found: error
        path: |
          ./Documentation/*
          ./Documentation/**/*

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documentation/html
