name: FaroEngine Windows Toolchain

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Toolchain:
    runs-on: windows-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Generate
      run: cmake ./Tools
      
    - name: Build
      run: cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FaroEngine
        if-no-files-found: error
        path: |
          Bin/*.exe
          Bin/*.dll
          Source/**/*

  BuildEngine:
    runs-on: windows-latest
    needs: Toolchain
    steps:
    - name: actions/download-artifact@master
      uses: actions/download-artifact@master
      with:
        name: FaroEngine

    - name: Generate
      run: Bin/FaroBuildTool.exe -generate -project Source/FaroEngine.faroproject.json
    
    - name: Build
      run: Bin/FaroBuildTool.exe -build -platform Windows x64 -project Source/FaroEngine.faroproject.json
