name: FaroEngine Windows Toolchain

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Toolchain:
    runs-on: windows-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate
      run: cmake ./Tools

    - name: Build
      run: cmake --build . --config Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: FaroEngine
        if-no-files-found: error
        path: |
          Bin/*.exe
          Bin/*.dll
          Source/**/*

  BuildEngine:
    runs-on: windows-latest
    needs: Toolchain
    steps:
    - name: actions/download-artifact@master
      uses: actions/download-artifact@master
      with:
        name: FaroEngine

    - name: Generate
      run: Bin/FaroBuildTool.exe -generate -project Source/FaroEngine.faroproject.json

    - name: Build
      run: Bin/FaroBuildTool.exe -build -platform Windows x64 -release -project Source/FaroEngine.faroproject.json

  Documentation:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Generate
      run: cmake ./Docs

    - name: Build
      uses: mattnotmitt/doxygen-action@v1.9.4
      with:
        doxyfile-path: 'Doxygen'
        working-directory: 'Docs'

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Documentation
        if-no-files-found: error
        path: |
          ./Documentation/*
          ./Documentation/**/*

  PublishDocumentation:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: Documentation
    steps:
    - name: actions/download-artifact@master
      uses: actions/download-artifact@master
      with:
        name: Documentation
        path: Documentation

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Documentation/html
